---

- name: Push data on the device
  hosts: "{{ device_id }}"
  connection: local

  gather_facts: false
  tasks:

    - name: data
      debug:
        msg: "data {{data}}"


    - set_fact:
        net_intfs: "{{  'name':data.name, 'description':data.description, 'enabled':data.enabled }}"

    - name: data short
      debug:
        msg: "{{ net_intfs }}"

    - name: Push Cisco IOS interface basics
      cisco.ios.ios_interfaces:
        config: "{{ net_intfs }}"
        state: replaced