---

- name: Push data on the device
  hosts: localhost
  connection: local

  gather_facts: false
  tasks:

    - name: Device
      debug:
        msg: "device {{device_id}}"

    - name: interface
      debug:
        msg: "device {{interface_id}}"
