---

- name: Push data on the device
  hosts: "{{ device_id }}"
  connection: local

  gather_facts: false
  tasks:

    - name: data
      debug:
        msg: "data {{data}}"

    - name: set facts
      set_fact: 
        data_json: "{{data | to_json }}" 

    - name: data description
      debug:
        msg: "data {{ data_json.description }}"


    - name: data name
      debug:
        msg: "data {{ data_json['name'] }}"

    - name: data enabled
      debug:
        msg: "data {{ data_json.enabled }}"

    - name: Push Cisco IOS interface basics
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ data.name }}"
            description: "{{ data.description }}"
            enabled: "{{ data.enabled }}"
        state: merged