---

- name: Push data on Cisco  device
  hosts: "{{ device_id }}"
  connection: local

  gather_facts: false
  tasks:

    - name: data name
      debug:
        msg: "data {{ data }}"

    - name: Push Cisco IOS interface basics
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ data_name }}"
            description: "{{ data_description }}"
            enabled: "{{ data_enabled }}"
        state: replaced