---

- name: Push data on the device
  hosts: "{{ device_id }}"
  connection: local

  gather_facts: false
  tasks:

    - name: data
      debug:
        msg: "data {{data}}"

    - name: Push Cisco IOS interface basics
      cisco.ios.ios_interfaces:
        - name: "{{ data.name }}"
          description: "{{ data.description }}"
          enabled: "{{ data.enabled }}"
        state: replaced